#!/bin/bash
# Hugging Face Authentication Setup

echo "🤗 Hugging Face Authentication Setup"
echo "===================================="
echo ""
echo "To authenticate with Hugging Face:"
echo ""
echo "1. Go to: https://huggingface.co/settings/tokens"
echo "2. Log in with: daiditenax@gmail.com"
echo "3. Create a new token with 'read' permissions"
echo "4. Copy the token"
echo ""
echo "Then run one of these commands:"
echo ""
echo "Option 1: Set environment variable (temporary):"
echo "export HF_TOKEN='your_token_here'"
echo ""
echo "Option 2: Use huggingface-cli (permanent):"
echo "huggingface-cli login"
echo ""
echo "Option 3: Add to .env file (permanent for this project):"
echo "echo 'HF_TOKEN=your_token_here' >> .env"
echo ""
echo "After authentication, make sure you have access to Gemma:"
echo "https://huggingface.co/google/gemma-2b"
echo "Click 'Agree and access repository' if prompted"